spring:
  jpa:
    database: MySQL
    show-sql: true
    hibernate:
      ddl-auto: create
  datasource:
    platform: mysql
    url: jdbc:mysql://localhost:3306/my_db
    username: system_abc
    password: yourpass
